// <auto-generated />
namespace TaskManager_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateNullablefiledTaskNo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateNullablefiledTaskNo));
        
        string IMigrationMetadata.Id
        {
            get { return "202002061340015_update Nullable filed Task No"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
